export const constants = {
  PERSONAL: "PERSONAL",
  STRANGER: "STRANGER",
  PERSONAL_CHAT: "PERSONAL_CHAT",
  PERSONAL_VIDEO: "PERSONAL_VIDEO",
  STRANGER_CHAT: "STRANGER_CHAT",
  STRANGER_VIDEO: "STRANGER_VIDEO",
  CHAT: "CHAT",
  VIDEO: "VIDEO",
  CALLE_TYPES: ["PERSONAL", "STRANGER"],
};
